// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/officers": {
            "get": {
                "description": "Get list of all security officers",
                "produces": ["application/json"],
                "tags": ["officers"],
                "summary": "Get all officers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Officer"}
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new security officer",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["officers"],
                "summary": "Create a new officer",
                "parameters": [
                    {
                        "description": "Officer data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/handlers.CreateOfficerInput"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"$ref": "#/definitions/models.Officer"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/officers/{id}": {
            "get": {
                "description": "Get a single security officer by ID",
                "produces": ["application/json"],
                "tags": ["officers"],
                "summary": "Get an officer by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Officer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/models.Officer"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            },
            "put": {
                "description": "Update an existing security officer",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["officers"],
                "summary": "Update an officer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Officer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Officer data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/handlers.UpdateOfficerInput"}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/models.Officer"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            },
            "delete": {
                "description": "Delete a security officer",
                "tags": ["officers"],
                "summary": "Delete an officer",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Officer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {"description": "No Content"},
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/shifts": {
            "get": {
                "description": "Get shifts with optional filters (date, officer_id, week_start)",
                "produces": ["application/json"],
                "tags": ["shifts"],
                "summary": "Get shifts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Date (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Officer ID",
                        "name": "officer_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Week start date (Sunday, YYYY-MM-DD)",
                        "name": "week_start",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {"$ref": "#/definitions/models.Shift"}
                        }
                    }
                }
            }
        },
        "/shifts/generate": {
            "post": {
                "description": "Generate the complete shift rota for a given week starting on Sunday",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["shifts"],
                "summary": "Generate rota for a week",
                "parameters": [
                    {
                        "description": "Week start date (must be Sunday)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/handlers.GenerateWeekRotaInput"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"type": "object"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/shifts/rotation": {
            "get": {
                "description": "Get which team is on which shift for a given week",
                "produces": ["application/json"],
                "tags": ["shifts"],
                "summary": "Get week rotation info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Week start date (Sunday, YYYY-MM-DD)",
                        "name": "week_start",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/models.WeekRotation"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/rota/week": {
            "get": {
                "description": "Get the full duty rota for a specific week with all officers and their shifts",
                "produces": ["application/json"],
                "tags": ["rota"],
                "summary": "Get complete weekly rota view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Week start date (Sunday, YYYY-MM-DD)",
                        "name": "week_start",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {"$ref": "#/definitions/handlers.WeekRotaResponse"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/rota/week/pdf": {
            "get": {
                "description": "Generate and download a PDF of the weekly duty rota",
                "produces": ["application/pdf"],
                "tags": ["rota"],
                "summary": "Download weekly rota as PDF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Week start date (Sunday, YYYY-MM-DD)",
                        "name": "week_start",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF file",
                        "schema": {"type": "file"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/admin/import-state": {
            "post": {
                "description": "Set the current rotation state to sync with existing manual schedule",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Import current manual schedule state",
                "parameters": [
                    {
                        "description": "Current schedule state",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/handlers.ImportCurrentStateInput"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"type": "object"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/admin/import-shifts": {
            "post": {
                "description": "Import historical or current shifts from manual schedule (JSON)",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Bulk import shifts (JSON)",
                "parameters": [
                    {
                        "description": "Shifts to import",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {"$ref": "#/definitions/handlers.BulkImportShiftsInput"}
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"type": "object"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/admin/template/officers": {
            "get": {
                "description": "Download a CSV template with headers and example data for officers",
                "produces": ["text/csv"],
                "tags": ["admin"],
                "summary": "Download CSV template for officer imports",
                "responses": {
                    "200": {
                        "description": "CSV file",
                        "schema": {"type": "file"}
                    }
                }
            }
        },
        "/admin/template/shifts": {
            "get": {
                "description": "Download a CSV template with headers and example data for shifts",
                "produces": ["text/csv"],
                "tags": ["admin"],
                "summary": "Download CSV template for shift imports",
                "responses": {
                    "200": {
                        "description": "CSV file",
                        "schema": {"type": "file"}
                    }
                }
            }
        },
        "/admin/import-officers/csv": {
            "post": {
                "description": "Upload a CSV file to bulk import officers",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Import officers from CSV file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"type": "object"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        },
        "/admin/import-shifts/csv": {
            "post": {
                "description": "Upload a CSV file to bulk import shifts",
                "consumes": ["multipart/form-data"],
                "produces": ["application/json"],
                "tags": ["admin"],
                "summary": "Import shifts from CSV file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {"type": "object"}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {"type": "object"}
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateOfficerInput": {
            "type": "object",
            "required": ["name", "role", "team"],
            "properties": {
                "name": {"type": "string"},
                "role": {"type": "string", "enum": ["sergeant", "female", "regular"]},
                "team": {"type": "integer", "minimum": 1, "maximum": 2}
            }
        },
        "handlers.UpdateOfficerInput": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "role": {"type": "string"},
                "team": {"type": "integer"}
            }
        },
        "handlers.ImportCurrentStateInput": {
            "type": "object",
            "required": ["week_start", "day_shift_team"],
            "properties": {
                "week_start": {"type": "string", "description": "Current week's Sunday (YYYY-MM-DD)"},
                "day_shift_team": {"type": "integer", "description": "Which team (1 or 2) is currently on day shift"}
            }
        },
        "handlers.BulkImportShiftsInput": {
            "type": "object",
            "required": ["shifts"],
            "properties": {
                "shifts": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/handlers.BulkImportShiftInput"}
                }
            }
        },
        "handlers.BulkImportShiftInput": {
            "type": "object",
            "required": ["name", "date", "shift_type", "status"],
            "properties": {
                "name": {"type": "string", "description": "Officer name"},
                "date": {"type": "string", "description": "YYYY-MM-DD"},
                "shift_type": {"type": "string", "enum": ["day", "night"]},
                "status": {"type": "string", "enum": ["on_duty", "off_duty"]}
            }
        },
        "handlers.GenerateWeekRotaInput": {
            "type": "object",
            "required": ["week_start"],
            "properties": {
                "week_start": {"type": "string", "description": "YYYY-MM-DD (must be Sunday)"}
            }
        },
        "models.Officer": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "name": {"type": "string"},
                "role": {"type": "string"},
                "team": {"type": "integer"},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        },
        "models.Shift": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "officer_id": {"type": "integer"},
                "officer": {"$ref": "#/definitions/models.Officer"},
                "date": {"type": "string"},
                "shift_type": {"type": "string", "enum": ["day", "night"]},
                "status": {"type": "string", "enum": ["on_duty", "off_duty"]},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        },
        "models.WeekRotation": {
            "type": "object",
            "properties": {
                "id": {"type": "integer"},
                "week_start": {"type": "string"},
                "day_shift_team": {"type": "integer"},
                "created_at": {"type": "string"},
                "updated_at": {"type": "string"}
            }
        },
        "handlers.WeekRotaResponse": {
            "type": "object",
            "properties": {
                "week_start": {"type": "string"},
                "week_end": {"type": "string"},
                "day_shift_team": {"type": "integer"},
                "night_shift_team": {"type": "integer"},
                "days": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/handlers.DayRota"}
                }
            }
        },
        "handlers.DayRota": {
            "type": "object",
            "properties": {
                "date": {"type": "string"},
                "day_of_week": {"type": "string"},
                "day_shift": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/handlers.OfficerDuty"}
                },
                "night_shift": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/handlers.OfficerDuty"}
                }
            }
        },
        "handlers.OfficerDuty": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "role": {"type": "string"},
                "status": {"type": "string", "enum": ["on_duty", "off_duty"]}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Security Rota API",
	Description:      "API for managing security officer rotas with weekly shift rotation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
